language: node_js
os:
  - linux
dist: "xenial"
node_js:
  - lts/*
install: 
  - yarn install
jobs:
  include:
    - script: tsc -p ./tsconfig.json
    - script: COVERALLS=coverage npm run coveralls
  allow_failures:
    - script: COVERALLS=coverage npm run coveralls
notifications:
  webhooks: https://coveralls.io/webhook