language: node_js
os:
  - linux
dist: "xenial"
node_js:
  - lts/*
install: 
  - yarn install
jobs:
  include:
    - script: npm run build
    - script: npm run test
    - script: npm run coverage
      after_script: npm run coveralls
  allow_failures:
    - script: npm run test
    - script: npm run coverage
notifications:
  webhooks: https://coveralls.io/webhook