on: ["push", "pull_request"]

name: Coveralls GitHub Action


jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: install packages 
      run:  npm install
    
    - name: install secrets
      run:  cp ./secrets/sample-config.json ./secrets/config.json
    
    - name: NYC Coverage Report
  # You may pin to the exact commit or the version.
  # uses: Tintef/nyc-reporter-action@ce03f0295fea4c06016b062ca6acc0ec56b94283
      uses: PoorlyDefinedBehaviour/nyc-reporter@v1
          with:
            command: "npm test"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
