on: ["push", "pull_request"]

name: Coveralls GitHub Action


jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: install packages 
      run:  npm install
    
    - name: install secrets
      run:  cp ./secrets/sample-config.json ./secrets/config.json
    
    - name: NYC Coverage Report
      run: npm run coveralls

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
